"""Tests for the Phase 1 CRM layer: timeline, ownership, tags, tasks, queues."""

from datetime import timedelta

from django.contrib.auth import get_user_model
from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from .models import (
    Activity,
    ActivityType,
    Business,
    Contact,
    LeadAssignment,
    LeadStatus,
    Tag,
    Task,
)
from .services import crm

User = get_user_model()


def make_business(**kw):
    kw.setdefault("place_id", f"place-{Business.objects.count() + 1}")
    kw.setdefault("name", "Test Cafe")
    return Business.objects.create(**kw)


class CrmServiceTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user("rep@example.com", "pw12345678")
        self.biz = make_business(international_phone="+27 11 555 0000")

    def test_log_activity_sets_last_activity_and_contacted(self):
        before = self.biz.last_activity_at
        self.assertIsNone(before)
        act = crm.log_activity(self.biz, user=self.user, kind=ActivityType.CALL, body="Rang owner")
        self.biz.refresh_from_db()
        self.assertEqual(act.kind, ActivityType.CALL)
        self.assertIsNotNone(self.biz.last_activity_at)
        # An outreach touch backfills contacted_at the first time.
        self.assertIsNotNone(self.biz.contacted_at)

    def test_note_does_not_set_contacted(self):
        crm.log_activity(self.biz, user=self.user, kind=ActivityType.NOTE, body="just a note")
        self.biz.refresh_from_db()
        self.assertIsNone(self.biz.contacted_at)
        self.assertIsNotNone(self.biz.last_activity_at)

    def test_change_status_logs_and_is_idempotent(self):
        self.assertTrue(crm.change_status(self.biz, LeadStatus.CONTACTED, user=self.user))
        self.biz.refresh_from_db()
        self.assertEqual(self.biz.status, LeadStatus.CONTACTED)
        self.assertIsNotNone(self.biz.contacted_at)
        self.assertEqual(self.biz.activities.filter(kind=ActivityType.STATUS).count(), 1)
        # No-op when status is unchanged.
        self.assertFalse(crm.change_status(self.biz, LeadStatus.CONTACTED, user=self.user))
        self.assertEqual(self.biz.activities.filter(kind=ActivityType.STATUS).count(), 1)

    def test_assign_lead_records_owner_history_and_activity(self):
        self.assertTrue(crm.assign_lead(self.biz, self.user, by=self.user))
        self.biz.refresh_from_db()
        self.assertEqual(self.biz.assigned_to, self.user)
        self.assertEqual(LeadAssignment.objects.filter(business=self.biz).count(), 1)
        self.assertEqual(self.biz.activities.filter(kind=ActivityType.ASSIGNMENT).count(), 1)
        # Re-assigning to same user is a no-op.
        self.assertFalse(crm.assign_lead(self.biz, self.user, by=self.user))

    def test_tag_add_remove(self):
        tag = Tag.objects.create(name="Hot Lead")
        self.assertTrue(crm.add_tag(self.biz, tag, user=self.user))
        self.assertFalse(crm.add_tag(self.biz, tag, user=self.user))
        self.assertIn(tag, self.biz.tags.all())
        self.assertTrue(crm.remove_tag(self.biz, tag, user=self.user))
        self.assertNotIn(tag, self.biz.tags.all())

    def test_task_create_and_complete(self):
        task = crm.create_task(self.biz, title="Follow up", assignee=self.user, by=self.user)
        self.assertFalse(task.is_done)
        self.assertEqual(self.biz.activities.filter(kind=ActivityType.TASK).count(), 1)
        crm.complete_task(task, user=self.user)
        task.refresh_from_db()
        self.assertTrue(task.is_done)
        self.assertIsNotNone(task.completed_at)
        self.assertEqual(self.biz.activities.filter(kind=ActivityType.TASK).count(), 2)


class TaskQueryTests(TestCase):
    def test_overdue_and_due_today_flags(self):
        biz = make_business()
        today = timezone.localdate()
        overdue = Task.objects.create(business=biz, title="late", due_date=today - timedelta(days=1))
        due = Task.objects.create(business=biz, title="now", due_date=today)
        self.assertTrue(overdue.is_overdue)
        self.assertFalse(overdue.is_due_today)
        self.assertTrue(due.is_due_today)
        self.assertFalse(due.is_overdue)


class TagSlugTests(TestCase):
    def test_slug_autogenerated_and_unique(self):
        a = Tag.objects.create(name="VIP Roaster")
        self.assertEqual(a.slug, "vip-roaster")
        b = Tag.objects.create(name="VIP Roaster!")  # different name, clashing slug base
        self.assertNotEqual(a.slug, b.slug)


class ViewTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_user(
            "admin@example.com", "pw12345678", role="admin", is_staff=True, is_superuser=True
        )
        self.rep = User.objects.create_user("rep@example.com", "pw12345678")
        self.biz = make_business(name="Bean Bar", international_phone="+27 11 555 1234")
        self.client.force_login(self.rep)

    def test_lead_detail_and_leads_pages_render(self):
        crm.assign_lead(self.biz, self.rep, by=self.rep)
        crm.log_activity(self.biz, user=self.rep, kind=ActivityType.NOTE, body="hello")
        Contact.objects.create(business=self.biz, name="Jane")
        resp = self.client.get(reverse("scraper:lead_detail", args=[self.biz.pk]))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Timeline")
        self.assertContains(resp, "Jane")
        resp = self.client.get(reverse("scraper:leads"))
        self.assertEqual(resp.status_code, 200)

    def test_work_page_renders(self):
        crm.create_task(self.biz, title="Call back", assignee=self.rep, by=self.rep,
                        due_date=timezone.localdate())
        resp = self.client.get(reverse("scraper:work"))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Call back")

    def test_lead_add_activity_creates_timeline_entry(self):
        url = reverse("scraper:lead_activity", args=[self.biz.pk])
        resp = self.client.post(url, {"kind": "call", "body": "Spoke to manager"})
        self.assertEqual(resp.status_code, 302)
        self.assertEqual(self.biz.activities.filter(kind="call").count(), 1)

    def test_lead_add_activity_rejects_empty_body(self):
        url = reverse("scraper:lead_activity", args=[self.biz.pk])
        self.client.post(url, {"kind": "note", "body": "   "})
        self.assertEqual(self.biz.activities.count(), 0)

    def test_assign_to_me(self):
        url = reverse("scraper:lead_assign", args=[self.biz.pk])
        self.client.post(url, {"assignee": "me"})
        self.biz.refresh_from_db()
        self.assertEqual(self.biz.assigned_to, self.rep)

    def test_add_contact(self):
        url = reverse("scraper:lead_add_contact", args=[self.biz.pk])
        self.client.post(url, {"name": "Jane Owner", "email": "jane@bean.bar", "is_primary": "on"})
        self.assertEqual(self.biz.contacts.count(), 1)
        self.assertTrue(self.biz.contacts.first().is_primary)

    def test_add_task_via_view(self):
        url = reverse("scraper:lead_add_task", args=[self.biz.pk])
        self.client.post(url, {"title": "Email pricing", "due_date": ""})
        self.assertEqual(self.biz.tasks.count(), 1)

    def test_bulk_assign_and_status(self):
        b2 = make_business(name="Second", national_phone="555")
        # Assign both to me.
        self.client.post(reverse("scraper:leads_bulk"), {
            "action": "assign", "assignee": "me", "ids": [self.biz.pk, b2.pk],
        })
        self.assertEqual(Business.objects.filter(assigned_to=self.rep).count(), 2)
        # Bulk status change.
        self.client.post(reverse("scraper:leads_bulk"), {
            "action": "status", "status": LeadStatus.CONTACTED, "ids": [self.biz.pk, b2.pk],
        })
        self.assertEqual(Business.objects.filter(status=LeadStatus.CONTACTED).count(), 2)

    def test_bulk_tag_and_task(self):
        tag = Tag.objects.create(name="Conference")
        self.client.post(reverse("scraper:leads_bulk"), {
            "action": "tag", "tag": tag.pk, "ids": [self.biz.pk],
        })
        self.assertIn(tag, self.biz.tags.all())
        self.client.post(reverse("scraper:leads_bulk"), {
            "action": "task", "task_title": "Bulk follow-up", "assignee": "me",
            "due_date": "2026-07-01", "ids": [self.biz.pk],
        })
        self.assertEqual(self.biz.tasks.filter(title="Bulk follow-up").count(), 1)

    def test_leads_filter_mine_and_ready(self):
        crm.assign_lead(self.biz, self.rep, by=self.rep)
        resp = self.client.get(reverse("scraper:leads_table"), {"view": "mine"})
        self.assertContains(resp, "Bean Bar")
        # "ready" needs NEW status + contactable; biz has a phone and is NEW.
        resp = self.client.get(reverse("scraper:leads_table"), {"view": "ready"})
        self.assertContains(resp, "Bean Bar")

    def test_tasks_page_scope_state(self):
        crm.create_task(self.biz, title="Mine open", assignee=self.rep, by=self.rep)
        resp = self.client.get(reverse("scraper:tasks"), {"scope": "mine", "state": "open"})
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Mine open")

    def test_tag_create_requires_admin(self):
        # Rep (viewer) is bounced.
        resp = self.client.post(reverse("scraper:tag_create"), {"name": "Nope", "color": "sky"})
        self.assertEqual(resp.status_code, 302)
        self.assertFalse(Tag.objects.filter(name="Nope").exists())
        # Admin can create.
        self.client.force_login(self.admin)
        self.client.post(reverse("scraper:tag_create"), {"name": "Yes", "color": "sky"})
        self.assertTrue(Tag.objects.filter(name="Yes").exists())

    def test_status_change_via_inline_endpoint_logs_activity(self):
        url = reverse("scraper:lead_status", args=[self.biz.pk])
        self.client.post(url, {f"status-{self.biz.pk}": LeadStatus.QUALIFIED})
        self.biz.refresh_from_db()
        self.assertEqual(self.biz.status, LeadStatus.QUALIFIED)
        self.assertTrue(self.biz.activities.filter(kind=ActivityType.STATUS).exists())
