# Generated by Django 6.0.6 on 2026-06-23 13:07

import django.db.models.deletion
import django.utils.timezone
import scraper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('search', 'Places search'), ('enrich', 'Website enrichment')], default='search', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('query', models.CharField(blank=True, help_text='Base text query, e.g. "coffee shops". Combined with each location.', max_length=255)),
                ('locations', models.JSONField(blank=True, default=list, help_text='List of place strings (e.g. cities). One search runs per entry.')),
                ('language', models.CharField(blank=True, max_length=8)),
                ('region', models.CharField(blank=True, max_length=8)),
                ('max_pages', models.PositiveSmallIntegerField(default=3, help_text='Pages of 20 results to fetch per location. Google returns at most 3 pages (~60 results) per query, so higher values stop early.')),
                ('auto_expand', models.BooleanField(default=False, help_text='Run multiple query variants per location to get past the 60/query cap.')),
                ('query_variants', models.JSONField(blank=True, default=list, help_text='Resolved list of queries run per location when auto_expand is on.')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('total', models.PositiveIntegerField(default=0, help_text='Total units of work.')),
                ('processed', models.PositiveIntegerField(default=0)),
                ('results_found', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=16)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', scraper.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('formatted_address', models.CharField(blank=True, max_length=1024)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('national_phone', models.CharField(blank=True, max_length=64)),
                ('international_phone', models.CharField(blank=True, max_length=64)),
                ('website', models.URLField(blank=True, max_length=1024)),
                ('google_maps_uri', models.URLField(blank=True, max_length=1024)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_total', models.PositiveIntegerField(default=0)),
                ('price_level', models.CharField(blank=True, max_length=32)),
                ('business_status', models.CharField(blank=True, max_length=32)),
                ('primary_type', models.CharField(blank=True, max_length=128)),
                ('types', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, db_index=True, max_length=128)),
                ('search_location', models.CharField(blank=True, help_text='The location string that surfaced this lead.', max_length=255)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('enrichment_status', models.CharField(choices=[('none', 'Not attempted'), ('pending', 'Queued'), ('done', 'Enriched'), ('failed', 'Failed'), ('no_website', 'No website')], db_index=True, default='none', max_length=16)),
                ('enrichment_error', models.TextField(blank=True)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost'), ('not_a_fit', 'Not a fit')], db_index=True, default='new', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('source_query', models.CharField(blank=True, max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='scraper.crawljob')),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['-first_seen'],
                'indexes': [models.Index(fields=['status'], name='scraper_bus_status_c4b670_idx'), models.Index(fields=['enrichment_status'], name='scraper_bus_enrichm_8fcd7d_idx'), models.Index(fields=['country'], name='scraper_bus_country_89d626_idx')],
            },
        ),
    ]
